import { TravelEntry } from '@modules/travel/domain/Types/TravelEntry';

export const mockTravelData: TravelEntry[] = [
    {
        id: '1',
        title: 'Aventura en Kioto',
        location: 'Japón',
        description: 'Templos antiguos, sakura y cultura samurái.',
        photos: ['https://picsum.photos/400?random=1'],
        dateStart: '2023-10-01',
        dateEnd: '2023-10-15',
        tags: ['cultura', 'aventura'],
    },
    {
        id: '2',
        title: 'Explorando Patagonia',
        location: 'Argentina',
        description: 'Montañas, glaciares y mucho trekking.',
        photos: ['https://picsum.photos/400?random=2'],
        dateStart: '2023-11-01',
        dateEnd: '2023-11-10',
        tags: ['naturaleza', 'aventura'],
    },
    {
        id: '3',
        title: 'Safari en Serengeti',
        location: 'Tanzania',
        description: 'Vida salvaje y paisajes impresionantes.',
        photos: ['https://picsum.photos/400?random=3'],
        dateStart: '2023-12-01',
        dateEnd: '2023-12-15',
        tags: ['naturaleza', 'aventura'],
    },
    {
        id: '4',
        title: 'Cultura en Marrakech',
        location: 'Marruecos',
        description: 'Zocos, palacios y gastronomía única.',
        photos: ['https://picsum.photos/400?random=4'],
        dateStart: '2024-01-01',
        dateEnd: '2024-01-10',
        tags: ['cultura', 'gastronomía'],
    },
    {
        id: '5',
        title: 'Relajación en Bali',
        location: 'Indonesia',
        description: 'Playas paradisíacas y templos antiguos.',
        photos: ['https://picsum.photos/400?random=5'],
        dateStart: '2024-02-01',
        dateEnd: '2024-02-15',
        tags: ['relajación', 'playa'],
    },
];
